---
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Publish Version

Resources:
  SNS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: src/templates/sns.yml

  Func1:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/func1
      Handler: index.handler
      Runtime: python2.7

  PublishVersion:
    Type: AWS::Serverless::Function
    # TODO: enabling multiple resources specification
    DependsOn: Func1
    Properties:
      CodeUri: src/handlers/func2
      Handler: index.handler
      Runtime: python2.7
      Policies:
        - arn:aws:iam::aws:policy/AWSLambdaFullAccess
      Events:
        Invoker:
          Type: SNS
          Properties:
            Topic: !GetAtt SNS.Outputs.TopicArn

  PublishVersion:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: src/templates/custom.yml
      Parameters:
        # TODO: enabling multiple resources specification
        FunctionName: !Ref Func1
        TopicArn: !GetAtt SNS.Outputs.TopicArn
