---
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Step Function Test

Resources:
  Func:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/handler
      Handler: handler.hello
      Runtime: python2.7
  InvokeLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: StepFunctionsAssumeRolePolicy
            Effect: Allow
            Principal:
              Service: !Sub states.${AWS::Region}.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaRole
  TestStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      RoleArn: !GetAtt InvokeLambdaRole.Arn
      DefinitionString: !Sub |-
        {
          "StartAt": "HelloWorld",
          "States": {
            "HelloWorld": {
              "Type": "Task",
              "Resource": "${Func.Arn}",
              "End": true
            }
          }
        }

Outputs:
  StateMachineArn:
    Value: !Ref TestStateMachine
  StateMachineName:
    Value: !GetAtt TestStateMachine.Name
