---
swagger: 2.0
info:
  title: ServerlessResizeApi
paths:
  /:
    get:
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Func.Arn}/invocations
        type: AWS_PROXY
        httpMethod: POST
