service: aws-python-test6

provider:
  name: aws
  runtime: python2.7
  stage: ${opt:stage}
  region: ap-northeast-1
  cfLogs: true

functions:
  index:
    handler: src/handlers/handler.hello
    events:
      - http:
          method: get
          path: whatever
          integration: lambda
          request:
            template:
              text/xhtml: '{ "stage": "$context.stage" }'
              application/json: '{ "httpMethod": "$context.httpMethod" }'
