service: anomaly-detection

frameworkVersion: ">=1.19.0 <2.0.0"

custom:
  config: ${{file(config.yml)}}

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${{self:custom.config.stage}}
  region: us-west-2
  memorySize: 128
  timeout: 5
  variableSyntax: "\\${{([ :a-zA-Z0-9._,\\-\\/\\(\\)]+?)}}"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sns:Publish
      Resource:
        Ref: ClickStreamEvent
    - Effect: Allow
      Action:
        - kinesis:GetRecords
        - kinesis:GetShardIterator
        - kinesis:DescribeStream
      Resource:
        Fn::GetAtt: [ KinesisBeaconOutputStream, Arn ]
    - Effect: Allow
      Action:
        - kinesis:ListStreams
      Resource:
        Fn::Join: [ "", [ "arn:aws:kinesis:", Ref: "AWS::Region", ":", Ref: "AWS::AccountId", ":stream/*" ] ]

package:
  individually: true
  exclude:
    - "**"

functions:
  func:
    handler: src/handlers/func/index.handler
    environment:
      TOPIC_ARN:
        Ref: ClickStreamEvent
    events:
      - stream:
          type: kinesis
          arn:
            Fn::GetAtt: [ KinesisBeaconOutputStream, Arn ]
          batchSize: 1
          startingPosition: LATEST
    package:
      include:
        - src/handlers/func/*.js

resources: ${{file(resource.yml)}}
