service: aws-python-test13

provider:
  name: aws
  runtime: python2.7
  stage: ${opt:stage}
  region: ap-northeast-1
  cfLogs: true

plugins:
  - serverless_swagger

custom:
  swagger_file: swagger.yml

functions:
  index:
    handler: handler.hello
    #events:
    #  - http: GET hello
