---
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: swagger-external

Parameters:
  Env:
    Type: String
    Default: dev
  S3Bucket:
    Type: String

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: General Configuration
        Parameters:
          - Env
          - S3Bucket
    ParameterLabels:
      Env:
        default: Env
      S3Bucket:
        default: S3 bucket

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionUri: src/api/swagger.yml
        #Bucket: !Ref S3Bucket
        #Key: swagger.yml
      StageName: !Ref Env
      Variables:
        FuncName: !Ref Func1
        AWSRegion: !Ref AWS::Region
        AWSAccountId: !Ref AWS::AccountId
        FuncArn: !GetAtt Func1.Arn

  Func1:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/func1
      Handler: index.handler
      Runtime: python2.7
      Events:
        PostApi:
          Type: Api
          Properties:
            Path: /
            Method: GET
            RestApiId: !Ref Api
