service: aws-python

provider:
  name: aws
  runtime: python2.7
  stage: dev
  region: ap-northeast-1

plugins:
  - serverless-plugin-diff

functions:
  hello:
    handler: handler.hello

resources:
  Resources:
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        #BucketName: knakayama-serverless-plugin-diff
        BucketName: knakayama-serverless-plugin-diff2
  Outputs:
     NewOutput:
       Description: Description for the output
       Value: Some output value
