---
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Nested Stack

Resources:
  Func:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/handler
      Handler: handler.hello
      Runtime: python2.7
  StepFunctions:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: src/templates/step-functions/template.yml
      Parameters:
        FuncArn: !GetAtt Func.Arn

Outputs:
  StateMachineArn:
    Value: !GetAtt StepFunctions.Outputs.StateMachineArn
  StateMachineName:
    Value: !GetAtt StepFunctions.Outputs.StateMachineName
