---
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Nested Stack

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: src/templates/vpc.yml
      Parameters:
        NameTagPrefix: nested-stack
        VPCCidr: 192.168.0.0/16
        SubnetCidr: 192.168.0.0/24

  Func1:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/func1
      Handler: handler.hello
      Runtime: python2.7
      Policies:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      VpcConfig:
        SecurityGroupIds:
          - !GetAtt VPC.Outputs.SecurityGroupId
        SubnetIds:
          - !GetAtt VPC.Outputs.SubnetId

  Func2:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/func2
      Handler: handler.hello
      Runtime: python2.7

  StepFunctions:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: src/templates/step-functions.yml
      Parameters:
        FuncArn: !GetAtt Func2.Arn

Outputs:
  StateMachineArn:
    Value: !GetAtt StepFunctions.Outputs.StateMachineArn
  StateMachineName:
    Value: !GetAtt StepFunctions.Outputs.StateMachineName
