---
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: CloudWatch Export Task

Parameters:
  FunctionName:
    Type: String
    Default: Func1

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Lambda Configuration
        Parameters:
          - FuncName
    ParameterLabels:
      FunctionName:
        default: Lambda Function Name

Resources:
  S3:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: src/templates/s3.yml

  Func1:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref FunctionName
      CodeUri: src/handlers/func1
      Handler: index.handler
      Runtime: python2.7
      Policies:
        - Version: 2012-10-17
          Statement:
            - Sid: CreateExportTaskPolicy
              Effect: Allow
              Action: logs:CreateExportTask
              Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${FunctionName}:log-stream:*
      Environment:
        Variables:
          FunctionName: !Ref FunctionName
          S3BucketName: !GetAtt S3.Outputs.S3BucketName
      Events:
        Timer:
          Type: Schedule
          Properties:
            Schedule: "cron(5 0 * * ? *)"
