---
AWSTemplateFormatVersion: "2010-09-09"
Description: Test1

Resources:
  DynamoDB:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: deviceId
          AttributeType: S
      KeySchema:
        - AttributeName: deviceId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      StreamSpecification:
        StreamViewType: NEW_IMAGE

Outputs:
  DynamoDBStreamArn:
    Value: !GetAtt DynamoDB.StreamArn
    Export:
      Name: !Sub ${AWS::StackName}-DynamoDBStreamArn
