---
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Plural Events

Resources:
  Func1:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/func1
      Handler: index.handler
      Runtime: python2.7
      Events:
        Timer1:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
        Timer2:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
        Timer3:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)
