Parameters:
  RetentionInDays:
    Type: Number
    Default: ${self:custom.config.retentionInDays}
  TableName:
    Type: String
    Default: ${env:TABLE_NAME}

Resources:
  DynamodbLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays:
        Ref: RetentionInDays

  TestTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Ref: TableName
      AttributeDefinitions:
        - AttributeName: testId
          AttributeType: S
      KeySchema:
        - AttributeName: testId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

Outputs:
  TableName:
    Value:
      Ref: TestTable
