service: localstack
custom:
  config: ${file(config.yml)}

frameworkVersion: ">=1.12.1 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${self:custom.config.stage}
  region: ${self:custom.config.region}
  cfLogs: true
  iamRoleStatements:
    - Sid: DynamoDBAccess
      Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - Fn::Join: [ "", [ "arn:aws:dynamodb:", Ref: "AWS::Region", ":", Ref: "AWS::AccountId", ":", "table/", Ref: TestTable ] ]

package:
  include:
    - src/handlers/*/*
    - src/handlers/*/lib/**
  exclude:
    - "**"

functions:
  dynamodb:
    handler: src/handlers/dynamodb/index.handler
    environment:
      TABLE_NAME: ${env:TABLE_NAME}
      DEFAULT_REGION: ${env:DEFAULT_REGION}
      HOSTNAME: ${env:HOSTNAME}

resources: ${file(${self:custom.config.resources})}
