service: cognito-test1
custom:
  config: ${file(config.yml)}

frameworkVersion: ">=1.12.1 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${self:custom.config.stage}
  region: ${self:custom.config.region}
  cfLogs: true

package:
  include:
    - src/handlers/*/*
    - src/handlers/*/lib/**
  exclude:
    - "**"

functions:
  func1:
    handler: src/handlers/func1/index.handler

resources: ${file(${self:custom.config.resources})}
