service: lambda-dlq-sqs-test

custom:
  sqs: LambdaDLQTest

provider:
  name: aws
  runtime: python2.7
  stage: dev
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource:
        - Fn::Join: [ ":", [ "arn:aws:sqs", Ref: "AWS::Region", Ref: "AWS::AccountId", "${self:custom.sqs}" ] ]

plugins:
  - serverless-plugin-lambda-dead-letter

functions:
  fail:
    handler: handler.fail
    deadLetter:
      sqs: ${self:custom.sqs}
    events:
      - schedule: rate(1 minute)
