---
swagger: 2.0
info:
  version: 2017-01-29T07:07:09Z
  title: dev-aws-sam-test1
basePath: /dev
schemes:
  - https
paths:
  /hello:
    get:
      responses: {}
      x-amazon-apigateway-integration:
        uri: arn:aws:apigateway:<region>:lambda:path/2015-03-31/functions/arn:aws:lambda:<region>:<accountid>:function:${stageVariables.LambdaFunctionName}/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
