---
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Test

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionUri: swagger.yml
      StageName: dev
      Variables:
        # NOTE: Before using this template, replace the <<region>> and <<account>> fields
        #       in Lambda integration URI in the swagger file to region and accountId
        #       you are deploying to
        LambdaFunctionName: !Ref LambdaFunction
        # not work
        AWSAccountId: !Ref AWS::AccountId
        AWSRegion: !Ref AWS::Region

  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/handler.hello
      Runtime: python2.7
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /hello
            Method: GET
      #  ProxyApiGreedy:
      #    Type: Api
      #    Properties:
      #      RestApiId: !Ref ApiGatewayApi
      #      Path: /{proxy+}
      #      Method: ANY
