service: aws-python

frameworkVersion: ">=1.6.0"

custom:
  config: ${file(config.${opt:stage}.yml)}

provider:
  name: aws
  runtime: python2.7
  stage: ${opt:stage}
  region: ap-northeast-1


functions:
  hello:
    handler: handler.hello

resources: ${file(resource.yml)}
