---
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: swagger-inline-2

Parameters:
  Env:
    Type: String
    Default: dev

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: General Configuration
        Parameters:
          - Env
    ParameterLabels:
      Env:
        default: Env

Resources:
  Api:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: src/templates/swagger.yml
      Parameters:
        Env: !Ref Env
        FuncArn: !GetAtt Func1.Arn

  Func1:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/func1
      Handler: index.handler
      Runtime: python2.7
      Events:
        PostApi:
          Type: Api
          Properties:
            Path: /
            Method: GET
            RestApiId: !Ref Api.Outputs.Name
