service: serverless-sam-demo

frameworkVersion: ">=1.12.1 <2.0.0"

custom:
  config: ${file(config.yml)}

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${self:custom.config.stage}
  region: ${self:custom.config.region}
  cfLogs: true
  iamRoleStatements:
    - Sid: DynamoDBAccess
      Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - Fn::Join: [ "", [ "arn:aws:dynamodb:", Ref: "AWS::Region", ":", Ref: "AWS::AccountId", ":", "table/", Ref: TestTable ] ]

package:
  include:
    - src/handlers/*/*
    - src/handlers/*/lib/**
  exclude:
    - "**"

plugins:
  - serverless-sam

functions:
  hello:
    handler: src/handlers/hello/index.handler
    environment:
      TABLE_NAME:
        Ref: TestTable

resources: ${file(${self:custom.config.resources})}
