service: aws-python-test2

provider:
  name: aws
  runtime: python2.7
  stage: ${opt:stage}
  region: ap-northeast-1
  cfLogs: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource:
        - { Fn::Join: [ ":", [ "arn:aws:dynamodb", "${self:provider.region}", Ref: "AWS::AccountId", "*" ] ] }

functions:
  create:
    handler: posts.create
    environment:
      TableName:
        Ref: myDynamoDBTable
    events:
      - http:
          path: posts/create
          method: post

resources: ${file(resources.yml)}
