frameworkVersion: ">=1.12.1 <2.0.0"

service: dynamodb-stream

custom:
  config: ${file(config.yml)}

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${self:custom.config.stage}
  region: ${self:custom.config.region}
  cfLogs: true

package:
  individually: true
  exclude:
    - "**"

functions:
  put:
    handler: src/handlers/put/index.handler
    role: LambdaPutRole
    environment:
      TABLE_NAME:
        Ref: TestTable
    events:
      - schedule: rate(1 minute)
    package:
      include:
        - src/handlers/put/index.js
        - src/handlers/put/lib/*
  stream:
    handler: src/handlers/stream/index.handler
    role: LambdaStreamRole
    package:
      include:
        - src/handlers/stream/index.js
        - src/handlers/stream/lib/*
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt: [ TestTable, StreamArn ]

resources: ${file(${self:custom.config.resources})}
