service: dynamodb-stream
custom:
  config: ${file(config.yml)}

frameworkVersion: ">=1.12.1 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${self:custom.config.stage}
  region: ${self:custom.config.region}
  cfLogs: true

package:
  include:
    - src/handlers/*/*
    - src/handlers/*/lib/**
  exclude:
    - "**"

functions:
  put:
    handler: src/handlers/put/index.handler
    role: LambdaPutRole
    environment:
      TABLE_NAME:
        Ref: TestTable
    events:
      - schedule: rate(1 minute)
  stream:
    handler: src/handlers/stream/index.handler
    role: LambdaStreamRole
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt: [ TestTable, StreamArn ]

resources: ${file(${self:custom.config.resources})}
