---
AWSTemplateFormatVersion: 2010-09-09
Description: Custom Stack

Parameters:
  FunctionName:
    Type: String

Resources:
  LambdaBasicExecRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: LambdaAssumeRolePolicy
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaFullAccess
  LambdaPublishVersion:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          from __future__ import print_function
          import cfnresponse
          import boto3
          import json
          client = boto3.client('lambda')
          def handler(event, context):
              if event['RequestType'] == 'Delete':
                  cfnresponse.send(event, context, cfnresponse.SUCCESS, {})
              function_name = event['ResourceProperties']['FunctionName']
              try:
                  code_sha256 = client.get_function(FunctionName=function_name)['Configuration']['CodeSha256']
              except Exception as e:
                  print(e)
                  cfnresponse.send(event, context, cfnresponse.FAILED, {})
              else:
                  try:
                      resp = client.publish_version(
                              FunctionName=function_name,
                              CodeSha256=code_sha256)
                  except Exception as e:
                      print(e)
                      cfnresponse.send(event, context, cfnresponse.FAILED, {})
                  else:
                      response_data = {'Response': json.dumps(resp)}
                      cfnresponse.send(event, context, cfnresponse.SUCCESS, response_data)
      Handler: index.handler
      Role: !GetAtt LambdaBasicExecRole.Arn
      Runtime: python2.7
  CustomPublishVersion:
    Type: Custom::PublishVersion
    Version: 1.0
    Properties:
      ServiceToken: !GetAtt LambdaPublishVersion.Arn
      FunctionName: !Ref FunctionName
