---
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS IoT Rules Engine Sample Stack

Parameters:
  InfraStackNamePrefix:
    Type: String
    Default: infra

  LambdaLogGroupNamePrefix:
    Type: String
    Default: /aws/lambda

Globals:
  Function:
    Handler: index.handler
    Runtime: python3.6
    AutoPublishAlias: live

Resources:
  WhereFunc:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub where-func-${AWS::StackName}
      CodeUri: src/handlers/where_func
      Role:
        Fn::ImportValue: !Sub ${InfraStackNamePrefix}-WhereFuncRoleArn
      Environment:
        Variables:
          TABLE_NAME:
            Fn::ImportValue: !Sub ${InfraStackNamePrefix}-DynamoDBTableName

  WhereFuncLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub ${LambdaLogGroupNamePrefix}/${WhereFunc}

  ActionFunc:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub action-func-${AWS::StackName}
      CodeUri: src/handlers/action_func
      Role:
        Fn::ImportValue: !Sub ${InfraStackNamePrefix}-ActionFuncRoleArn
      Events:
        IoTRule:
          Type: IoTRule
          Properties:
            AwsIotSqlVersion: 2016-03-23
            Sql: !Sub |
              SELECT *
              FROM '$aws/things/+/shadow/update'
              WHERE aws_lambda("${WhereFunc.Alias}", {"deviceId": topic(3)}).isIllegal <> True

  WhereFuncIoTRuleInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref WhereFunc.Alias
      Principal: iot.amazonaws.com
      SourceArn: !GetAtt ActionFuncIoTRule.Arn
      SourceAccount: !Ref AWS::AccountId
      Action: lambda:InvokeFunction

  ActionFuncLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub ${LambdaLogGroupNamePrefix}/${ActionFunc}
