service: dynamodb-local

frameworkVersion: ">=1.12.1 <2.0.0"

custom:
  config: ${file(config.yml)}
  dynamodb:
    start:
      port: ${self:custom.config.port}
      inMemory: true
      migrate: true
      seed: true
    seed:
      test:
        sources:
          - table: ${self:custom.config.tableName}
            sources:
              - seed.json

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${self:custom.config.stage}
  region: ${self:custom.config.region}
  cfLogs: true
  iamRoleStatements:
    - Sid: DynamoDBAccess
      Effect: Allow
      Resource:
        - Fn::Join: [ "", [ "arn:aws:dynamodb:", Ref: "AWS::Region", ":", Ref: "AWS::AccountId", ":", "table/", Ref: TestTable ] ]
      Action:
        - dynamodb:*

package:
  include:
    - src/handlers/*/*
    - src/handlers/*/lib/**
  exclude:
    - "**"

plugins:
  - serverless-dynamodb-local
  - serverless-offline

functions:
  dynamodb:
    handler: src/handlers/dynamodb/index.handler
    environment:
      TABLE_NAME: ${self:custom.config.tableName}
      PORT: ${self:custom.config.port}

resources: ${file(${self:custom.config.resources})}
