frameworkVersion: ">=1.5.0"

service: test

provider:
  name: aws
  runtime: python2.7
  cfLogs: true

plugins:
  - serverless-python-requirements

custom:
  dockerizePip: true

functions:
  hello:
    handler: handler.hello
