service: custom-domain

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-northeast-1

plugins:
  - serverless-plugin-custom-domain

custom:
  domain: ${env:MY_DOMAIN}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
